// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV5O8fGKB0KUaALPnpZrolvyTtbQU5U6k',
    appId: '1:592629973679:web:91bc3fcbd506c6eb010a5a',
    messagingSenderId: '592629973679',
    projectId: 'my-project-1572786585550',
    authDomain: 'my-project-1572786585550.firebaseapp.com',
    storageBucket: 'my-project-1572786585550.firebasestorage.app',
    measurementId: 'G-PGPBCNR4RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrr4ZJesSKpMKvuMLHhQ2Mp1jfaxk9PB4',
    appId: '1:592629973679:android:9a3762b77e021b34010a5a',
    messagingSenderId: '592629973679',
    projectId: 'my-project-1572786585550',
    storageBucket: 'my-project-1572786585550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYkzN4rw-RlVbel_MD3Fg2AnNMlyQwWk',
    appId: '1:592629973679:ios:6759caeefbe59073010a5a',
    messagingSenderId: '592629973679',
    projectId: 'my-project-1572786585550',
    storageBucket: 'my-project-1572786585550.firebasestorage.app',
    iosBundleId: 'com.example.mapPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLYkzN4rw-RlVbel_MD3Fg2AnNMlyQwWk',
    appId: '1:592629973679:ios:6759caeefbe59073010a5a',
    messagingSenderId: '592629973679',
    projectId: 'my-project-1572786585550',
    storageBucket: 'my-project-1572786585550.firebasestorage.app',
    iosBundleId: 'com.example.mapPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV5O8fGKB0KUaALPnpZrolvyTtbQU5U6k',
    appId: '1:592629973679:web:c649eed448b8abae010a5a',
    messagingSenderId: '592629973679',
    projectId: 'my-project-1572786585550',
    authDomain: 'my-project-1572786585550.firebaseapp.com',
    storageBucket: 'my-project-1572786585550.firebasestorage.app',
    measurementId: 'G-3WSSZNQB8V',
  );
}
